### ISSUE TITLE
GW2Launcher crashing when selecting tomorrow's daily

### ISSUE THREAD

**Issue by Ganondolf** [Healix/Gw2Launcher#11]
Opening the side panel and selecting tomorrow's daily result in a crash. Launching the program in debug mode from Visual Studio gives the error:
```C#
System.IndexOutOfRangeException
  HResult=0x80131508
  Messaggio=Indice oltre i limiti della matrice.
  Origine=Gw2Launcher
  Analisi dello stack:
   at Gw2Launcher.UI.formDailies.SetupControls(Dailies dailies) in C:\Users\<user>\Documents\GitHub\Gw2Launcher\Gw2Launcher\UI\formDailies.cs:line 745
   at Gw2Launcher.UI.formDailies.<GetDailies>d__60.MoveNext() in C:\Users\<user>\Documents\GitHub\Gw2Launcher\Gw2Launcher\UI\formDailies.cs:line 1005
```

**Comment by Healix** [comment]
Fixed in the recent release. I had assumed it wasn't possible to have that many low level dailies.
