### ISSUE TITLE
Latest version occasionally made cursor crawl suspect high cpu usage causes it

### ISSUE THREAD

**Issue by Rainrainraind** [Healix/Gw2Launcher#309]
Hi, after updating to the latest version of GW2Launcher today, occasionally when launching a few account at the same time, sometimes my cursor became laggy for a few seconds.. and that it happened over 3-4 times, so I'm pretty sure it's due to the software and not caused by my System.  

here's the log if it helps
[04/27/2023 22:47:28.183] System.InvalidOperationException: Cannot process request because the process (10536) has exited.
   at System.Diagnostics.Process.GetProcessTimes()
   at System.Diagnostics.Process.get_StartTime()
   at Gw2Launcher.Client.Launcher.WindowWatcher.<EnumerateChildProcesses>d__1b8.MoveNext()
   at Gw2Launcher.Client.Launcher.WindowWatcher.GetRendererProcess(Process parent, Process[] result)
   at Gw2Launcher.Client.Launcher.WindowWatcher.WaitForHostProcesses(Process process, IntPtr window, HostType hostType, Process host, Boolean waitUntilLoaded, Int32 childCount, Func`1 onContinue)
   at Gw2Launcher.Client.Launcher.WindowWatcher.WatchWindow()
   at Gw2Launcher.Client.Launcher.WindowWatcher.WatchWindow2()

**Comment by Healix** [comment]
Use the task manager (ctrl+shift+esc) to verify which processes have high CPU usage.

Check if CoherentUI has the same problem by adding -usecoherent to the arguments under Settings > Guild Wars 2 > Launch options. If you were already using CoherentUI, test CEF instead. (CoherentUI is more efficient than CEF)

Judging by the log (it's a week old), you were previously using the beta version, since logging at that specific point was something I temporarily added to it. The previous beta version and the current release/beta are almost identical, with the main changes related to how automatic logins work with CEF.

You can access the log by right clicking any account > Tools > Log, but it's unlikely to reveal anything related to high CPU usage.
